openapi: 3.1.0
info:
  title: Description
  description: |
    Example of using spring boot
  version: 1.0.0
paths:
  /books:
    get:
      summary: List of books
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  authorName:
                    type: string